#Autostart

exec-once=noctalia
exec-once=hypridle
exec-once=~/.config/tuxedo/todo-daemon.sh			#script running todo-daemon checking reminders
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &	#polkit agent for 'click to mount on explorer' support
exec-once = gnome-keyring-daemon --start --components=secrets,ssh	#keyring support for some app secrets
exec-once = foot --server						#run foot terminal as server
#exec-once=~/tock-daemonv2.sh						#script running tock reminder daemon - activity tracking

