#Autostart
exec-once=~/.config/scripts/random-wall.sh          #random wallpaper script using swaybg
exec-once=~/.config/scripts/run-waybar.sh           #script running waybar
exec-once=~/.config/scripts/run-swayidle.sh         #script running swayidle
exec-once=~/.config/scripts/run-audio-inhibit.sh    #script to ensure running audio inhibit
exec-once=~/.config/scripts/battery_notify.sh       #battery-charger notifications
exec-once=~/.config/scripts/run-cliphist.sh         #script running clipboard history
exec-once=~/.config/scripts/todo-daemon.sh          #script running todo-daemon checking reminders
exec-once=gnome-keyring-daemon --start --components=secrets,ssh         #keyring support for some app secrets
exec-once=foot -s                                       #run foot terminal as server
exec-once=mako                                          #mako - notification daemon

