# More option see https://github.com/DreamMaoMao/mango/wiki/

#config sources
source=~/.config/mango/autostart.conf
#source=~/.config/mango/autostart-noctalia.conf
source=~/.config/mango/lookandfeel.conf
source=~/.config/mango/inputs.conf
source=~/.config/mango/keybinds.conf
source=~/.config/mango/layouts.conf

#Xwayland 
xwayland_persistence=0

# layer rule
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi

# tag rule
#tagrule=id:2,layout_name:scroller

#window rules
#windowrule=Parameter:Values,title:Values
#windowrule=Parameter:Values,Parameter:Values,appid:Values,title:Values
windowrule=isfloating:1,title:bluetui-float
windowrule=isfloating:1,title:fsel
windowrule=isfloating:1,appid:pavucontrol
windowrule=isfloating:1,width:1400,height:700,title:Tuxedo
windowrule=isfloating:1,width:1000,height:800,title:auto-cpufreq-stats
windowrule=isfloating:1,title:lenovo-battery-modes
windowrule=isfloating:1,width:1200,height:500,title:habits
windowrule=isfloating:1,width:1200,height:500,title:clipboard
windowrule=isfloating:1,width:1000,height:800,title:clipse
windowrule=isfloating:1,title:Network Connections
windowrule=isfloating:1,title:Timer
windowrule=isfloating:1,title:galculator
windowrule=isfloating:1,title:tock-reminder
#windowrule=isfloating:1,width:320,height:180,title:Picture in picture
windowrule=isfloating:1,width:480,height:270,title:Picture in picture
#windowrule=isfloating:1,width:640,height:360,title:Picture in picture
windowrule=isfloating:1,width:1000,height:800,title:wlctl - Wifi manager





