[main]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x5\xd3\0\0\x4\0\0\0\0\0\0\0\0\0\0\0\x5\xd3\0\0\x4\0\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x5\xd3\0\0\x4\0)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x5\xd4\0\0\x3\xeb\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[notification]
app=true
donation_message=true
show_msg=true
show_name=true
show_photo=true

[onboarding]
completed=true
last_environment=local
version=2

[system]
quit_in_close=true
spellCheckers=true
start_background=false
start_system=false
theme=dark
wayland=true

[website]
open_page=false
